// KeybordStudio V1 - Body Generator Hint Descriptions & Video Mappings
// tooltip/body/hints.js

export const bodyHintsJa = {
    body_hint_layout: "キーボードの配列サイズを選択します。60%〜フルサイズ、Alice配列などに対応。",
    body_hint_layout_standard: "キーレイアウトの規格を選択します。ANSI（US配列）、ISO（EU配列）、JIS（日本語配列）。",
    body_hint_pitch: "キースイッチ間の中心距離を設定します。標準は19.05mmです。",
    body_hint_kle: "Keyboard Layout Editor（KLE）のRawDataを貼り付けて、カスタム配列を読み込みます。",
    body_hint_wkl: "Windowsキーを省略したWinkeyless配列にします。",
    body_hint_hhkb: "HHKB風のブロッカーを追加します。",
    body_hint_mount: "スイッチプレートの取り付け方式を選択します。打鍵感や構造に影響します。",
    body_hint_standoff: "トレイマウント用のスタンドオフ（支柱）の寸法を設定します。",
    body_hint_gasket: "ガスケットマウント用のタブ設定です。柔軟な打鍵感を実現します。",
    body_hint_bezel_top: "ケース上部のベゼル幅を設定します。広くするとロゴなどを配置できます。",
    body_hint_bezel_bottom: "ケース下部のベゼル幅を設定します。",
    body_hint_bezel_side: "ケース左右のベゼル幅を設定します。",
    body_hint_corner: "ケースの四隅の丸み（フィレット）を設定します。値を大きくすると丸くなります。",
    body_hint_wall: "ケースの壁の厚みを設定します。強度と重さに影響します。",
    body_hint_profile_type: "ケースのプロファイルを選択します。High Profile、Low Profile、Floating Keyに対応。",
    body_hint_bottom_thick: "ケース底面の厚みを設定します。薄くすると軽量化できますが強度が落ちます。",
    body_hint_tilt: "キーボードのタイピング角度を設定します。0°〜15°の範囲で調整可能です。",
    body_hint_neg_tilt: "手前が高くなる逆チルト（ネガティブチルト）にします。人間工学的な配置です。",
    body_hint_feet: "折りたたみ式の角度調節足を追加します。段階的に角度を変更できます。",
    body_hint_rubber_pads: "底面にゴム足を追加して滑り止めにします。",
    body_hint_comfort_edge: "手前のエッジを丸くして、手首への負担を軽減します。",
    body_hint_usb: "USBポートの形状を選択します。USB-C、Micro-USB、Mini-USB、TRRSに対応。",
    body_hint_usb_pos_x: "USBポートの横方向の位置を調整します。",
    body_hint_usb_pos_y: "USBポートの高さ位置を調整します。",
    body_hint_port_margin: "USBポート開口部の余裕（マージン）を設定します。ケーブルの抜き差しに影響します。",
    body_hint_pcb_clearance: "PCB下のクリアランスを設定します。配線やコントローラーのスペースを確保します。",
    body_hint_ribs: "ケース内部に補強リブを追加して構造的な強度を高めます。",
    body_hint_battery: "Bluetooth対応のバッテリー収納スペースを追加します。位置も調整可能です。",
    body_hint_tolerance: "3Dプリントの公差を設定します。上下ケースの嵌合精度に影響します。",
    body_hint_insert_nut: "インサートナット用の穴径を選択します。M2〜M4のネジ穴に対応。",
    body_hint_split: "大型ケースを分割して小さなプリンターでも出力できるようにします。",
    body_hint_mouse_ear: "角の反りを防止するマウスイヤー（接着面積増加）を追加します。",
    body_hint_encoder: "ロータリーエンコーダー用の取り付け穴を追加します。音量調節やスクロールに便利。",
    body_hint_oled: "OLEDディスプレイ用の表示窓を追加します。レイヤー情報やカスタム表示に使用。",
    body_hint_tripod: "1/4インチ三脚穴を追加します。展示やストリーミング配信に便利です。",
    body_hint_colors: "各パーツの色をAMSスロットから設定します。マルチカラー3Dプリント用です。",
    body_hint_export: "ケースの3Dモデルをエクスポートします。STL・3MF形式に対応しています。"
};

export const bodyHintsEn = {
    body_hint_layout: "Select the keyboard layout size. Supports 60% to full-size, Alice, and more.",
    body_hint_layout_standard: "Select the key layout standard: ANSI (US), ISO (EU), or JIS (Japanese).",
    body_hint_pitch: "Set the center-to-center distance between switches. Standard is 19.05mm.",
    body_hint_kle: "Paste Keyboard Layout Editor (KLE) Raw Data to import a custom layout.",
    body_hint_wkl: "Remove Windows keys for a Winkeyless layout.",
    body_hint_hhkb: "Add HHKB-style blockers.",
    body_hint_mount: "Select the switch plate mounting method. Affects typing feel and structure.",
    body_hint_standoff: "Configure standoff dimensions for tray mount.",
    body_hint_gasket: "Configure gasket tab settings for a flexible typing experience.",
    body_hint_bezel_top: "Set the top bezel width. A wider bezel allows space for logos or decorations.",
    body_hint_bezel_bottom: "Set the bottom bezel width.",
    body_hint_bezel_side: "Set the left/right bezel width.",
    body_hint_corner: "Set the corner radius (fillet) of the case. Higher values = rounder corners.",
    body_hint_wall: "Set the case wall thickness. Affects strength and weight.",
    body_hint_profile_type: "Select the case profile: High Profile, Low Profile, or Floating Key.",
    body_hint_bottom_thick: "Set the bottom panel thickness. Thinner = lighter but less rigid.",
    body_hint_tilt: "Set the typing angle. Adjustable from 0 to 15 degrees.",
    body_hint_neg_tilt: "Enable reverse (negative) tilt where the front is raised. Ergonomic design.",
    body_hint_feet: "Add foldable tilt feet with adjustable angle stages.",
    body_hint_rubber_pads: "Add rubber pads to the bottom for grip and stability.",
    body_hint_comfort_edge: "Round the front edge to reduce wrist strain during typing.",
    body_hint_usb: "Select USB port type: USB-C, Micro-USB, Mini-USB, or TRRS.",
    body_hint_usb_pos_x: "Adjust the horizontal position of the USB port.",
    body_hint_usb_pos_y: "Adjust the vertical position of the USB port.",
    body_hint_port_margin: "Set the port opening margin. Affects cable plug/unplug clearance.",
    body_hint_pcb_clearance: "Set the clearance below the PCB for wiring and controllers.",
    body_hint_ribs: "Add internal reinforcement ribs for structural strength.",
    body_hint_battery: "Add a battery compartment for Bluetooth builds. Position is adjustable.",
    body_hint_tolerance: "Set the 3D print tolerance. Affects the fit between top and bottom case.",
    body_hint_insert_nut: "Select insert nut hole diameter. Supports M2 to M4 screw holes.",
    body_hint_split: "Split large cases into sections for smaller printer beds.",
    body_hint_mouse_ear: "Add mouse ears to prevent corner warping during printing.",
    body_hint_encoder: "Add a rotary encoder mounting hole. Great for volume control or scrolling.",
    body_hint_oled: "Add an OLED display window cutout. For layer info or custom displays.",
    body_hint_tripod: "Add a 1/4-inch tripod mount hole. Useful for display or streaming.",
    body_hint_colors: "Set part colors from AMS slots for multi-color 3D printing.",
    body_hint_export: "Export the case 3D model in STL or 3MF format."
};

export const bodyHintVideos = {
    // Body hint videos will be added as video files are created
    // Example entries (uncomment when videos are available):
    // body_hint_layout: { type: 'video', src: 'videos/bodyhint/レイアウト.mp4' },
    // body_hint_mount: { type: 'video', src: 'videos/bodyhint/マウント方式.mp4' },
};
