// KeybordStudio V1 - Keycap Generator Hint Descriptions & Video Mappings
// tooltip/keycap/hints.js

export const keycapHintsJa = {
    hint_f1_notice: "Wikiで詳しく見る",
    hint_lang: "表示言語を日本語または英語に切り替えます。",
    hint_section_jump: "設定したい項目へ素早く移動します。",
    hint_search: "設定項目名で検索し、該当箇所をハイライトします。",
    hint_stats: "現在の設定に基づいた、フィラメントの概算重量とコストを表示します。クリックで材料設定を開閉できます。",
    hint_unit_size: "1Uの基準サイズを設定します。通常は19.05mmですが、Choc系などは小さく設定します。",
    hint_key_size: "キーキャップの横幅を設定します。1.0(通常)、2.0(BackSpace)、6.25(Space)など。",
    hint_stabilizer: "2U以上のキーに付くスタビライザーの位置設定です。基本はAutoで問題ありませんが、特殊な配置の場合はCustomで調整します。",
    hint_profile: "キーキャップの全体形状（プロファイル）を選択します。Cherry, OEM, SA, XDA, DSAに対応しています。",
    hint_row: "キーの高さと傾斜角度（R1〜R4）を設定します。プロファイルによって形状が異なります。",
    hint_fillet: "キーキャップの四隅を丸くします（Squircle形状）。値を大きくすると丸くなります。",
    hint_wall_thick: "キーキャップ側面の厚みを設定します。薄すぎると強度が落ち、厚すぎるとスイッチと干渉する場合があります。",
    hint_rib_shorten: "内部のリブ（補強）の下端をどのくらい持ち上げるか設定します。LEDとの干渉を防ぐ場合などに調整します。",
    hint_enable_ribs: "内部に十字の補強壁を作成します。強度が向上し、反りを防ぎます。",
    hint_homing_bump: "FキーやJキーに付いている、指の感触で位置を知るための突起を作成します。",
    hint_bump_type: "突起の形状を『丸型』か『バー（長方形）』から選択します。",
    hint_key_shape: "キーキャップの基本形状を選択します。四角形、角丸、円形、多角形、星形、ISO Enter（L字形）に対応しています。",
    hint_taper: "キーキャップ天面の広さを調整します。値を小さくすると台形がきつくなります。",
    hint_dish_type: "指を置く天面のくぼみ形状を設定します。円筒(Cylindrical)、球(Spherical)、平坦(Flat)から選べます。",
    hint_texture: "表面にザラザラや模様などのテクスチャを自動生成します。",
    hint_texture_global: "テクスチャを天面だけでなく、側面を含むキーキャップ全体に適用します。",
    hint_twist: "キーキャップ全体をねじります。Artisanキーキャップ作成などに使えます。",
    hint_tilt: "天面の傾きをX軸・Z軸方向へ手動で微調整します。",
    hint_img_upload: "PNGまたはJPG画像をアップロードして、キーキャップの表面にテクスチャとして貼り付けます。好きな柄や写真をキーキャップの模様にできます。",
    hint_custom_font: "Facetype.jsなどで変換した『JSON形式』のフォントファイルを読み込みます。※PCに入っているTTFやOTFファイルは直接使用できません。",
    hint_stem_diameter: "スイッチに挿す軸の外側の太さを調整します。標準は5.5mmです。",
    hint_clearance: "十字穴の隙間（公差）を設定します。きつくて入らない場合は値を大きくしてください。",
    hint_stem_ext: "ステムだけを底面より長く伸ばします。特殊なスイッチや高さ調整に使用します。",
    hint_box_stem: "十字ステムの周りを四角い壁で囲み、強度と防塵性を高めます（Kailh Boxスイッチ風）。",
    hint_lego_stud: "天面にレゴブロック互換のポッチを追加します。",
    hint_enable_text: "文字の生成をON/OFFします。",
    hint_text_input: "刻印したい文字を入力します。改行すると2行になります。",
    hint_font: "刻印に使用するフォントを選択します。",
    hint_text_mode: "Emboss(浮き出し)、Engrave(彫り込み)、Double-Shot(別パーツ化)、Lithophane(バックライト透過)から選択します。",
    hint_text_height: "文字の厚みを設定します。Double-Shotの場合は埋め込む深さになります。",
    hint_conform: "キーキャップの天面のカーブに沿って文字を変形させます。",
    hint_align_preset: "中央、左上、右下などの定位置へワンクリックで文字を移動させます。",
    hint_text2: "メイン文字とは別に、右下などに小さな文字を追加します。",
    hint_side_print: "キーキャップの手前側面（フロント）に文字を入れます。",
    hint_svg_upload: "ベクター画像(.svg)を読み込んで刻印します。ロゴやアイコンに最適です。",
    hint_svg_mode: "SVGの処理方法を選びます。Double-Shotにするとマルチカラー印刷用に別パーツとして出力できます。",
    hint_strap_hole: "キーキャップに貫通穴をあけて、ペンダントやキーホルダーとして使えるようにします。位置(X/Z)・穴径・形状（円/長穴）を自由に変更でき、長穴では長さと回転角度も指定できます。入力中は穴の位置が赤い半透明シリンダーでプレビューされ、操作を止めると実際に穴が開きます。",
    // (Phase 11 cleanup: hint_workflow_guide / hint_qa_bar / hint_advanced_mode removed — UI deleted)
    hint_colors: "プレビュー画面上の色を変更します。※STL出力には影響しませんが、OBJ/3MF出力時には反映されます。",
    hint_url_share: "現在の設定をURLにエンコードしてコピーします。SNSなどで共有できます。",
    hint_quick_save: "現在の設定をブラウザに一時的に保存します。",
    hint_export_json: "設定をファイルとして保存します。後で読み込んだり、他の人と共有できます。",
    hint_import_json: "保存した設定ファイルを読み込みます。複数ファイルをドラッグ＆ドロップすると一括でリストに追加されます。",
    hint_print_orient: "3Dプリント時の向きに合わせて、モデル全体を回転させます。",
    hint_export_stl: "一般的な3Dプリンター用の形式(.stl)で保存します。",
    hint_export_3mf: "色情報を含んだ形式(.3mf)で保存します。Bambu Labなどのマルチカラー印刷に最適です。",
    hint_export_parts: "パーツを個別にSTL出力します。異なる色のフィラメントで印刷する場合などに使います。",
    hint_batch_list: "ここにカンマ区切り（A,B,C...）で文字を入れると、現在の設定で順番に自動生成します。",
    hint_batch_run: "リストの文字を連続で生成し、まとめてダウンロードします。",
    hint_randomizer: "すべてのパラメータをランダムに変更します。新しいアイデア探しに。",
    hint_reset: "すべての設定を初期状態に戻します。",
    hint_import_stl: "自作の3Dモデル(.stl)を読み込んで合成します。",
    hint_import_op: "Union（結合）は盛り上げ、Subtract（型抜き）は彫り込みに使用します。※Subtractは処理時間がかかります。",
    hint_simple_mode: "簡単モードでは、初心者向けに必要最小限の設定項目のみ表示します。細かい設定はV65のデフォルト値を使用します。",
    hint_dimension_lines: "3Dビュー上にキーキャップの寸法線を表示します。印刷前のサイズ確認に便利です。",
    hint_layer_color: "Bambu Lab AMSなどでフィラメント交換時の色の変化をシミュレーションします。",
    hint_visual_presets: "よく使うキー（WASD、矢印キーなど）をワンクリックで設定できます。",
    hint_stock_icons: "よく使うアイコン（矢印、再生、Commandキーなど）が内蔵されています。SVGを探す手間を省けます。",
    hint_tolerance_test: "プリンターの公差テスト用のステムを生成します。最適なクリアランス値を見つけるのに便利です。",
    hint_sprue_kit: "複数のキーキャップをプラモデルのランナーのように連結して出力します。ギフトや販売に最適。",
    hint_simple_key_size: "よく使うキーサイズをボタンで簡単に選択できます。",
    hint_snapshot: "現在の3Dビューを画像として保存します。",
    hint_gallery_open: "保存したプリセットのギャラリーを開きます。",
    hint_gallery_save: "現在の設定をギャラリーに保存します。",
    hint_font_manager: "カスタムフォント(.ttf/.otf/.woff)の管理ダイアログを開きます。",
    hint_svg_manager: "カスタムSVGの管理ダイアログを開きます。",
    hint_gumball: "テキストやSVG、インポートしたモデルの位置をドラッグで調整できます。",
    hint_toggle_text: "3Dビュー上の文字の表示/非表示を切り替えます。",
    hint_toggle_svg: "3Dビュー上のSVGの表示/非表示を切り替えます。",
    hint_stem_type: "キースイッチの軸タイプを選択します。Cherry MX、Kailh Choc、Topre、Alpsなど対応しています。",
    hint_click_place: "ONにしてモデル上をクリックすると、文字やアイコンがその位置に移動します。直感的な配置が可能です。"
};

export const keycapHintsEn = {
    hint_f1_notice: "View details on Wiki",
    hint_lang: "Switch display language between Japanese and English.",
    hint_section_jump: "Quickly jump to the section you want to configure.",
    hint_search: "Search settings by name and highlight matches.",
    hint_stats: "Shows estimated filament weight and cost based on current settings. Click to open/close material settings.",
    hint_unit_size: "Set the base size for 1U. Usually 19.05mm, but smaller for Choc switches etc.",
    hint_key_size: "Set the keycap width. 1.0 (normal), 2.0 (BackSpace), 6.25 (Space), etc.",
    hint_stabilizer: "Position settings for stabilizers on 2U+ keys. Auto works for most cases, use Custom for special layouts.",
    hint_profile: "Select the overall keycap shape (profile). Supports Cherry, OEM, SA, XDA, DSA.",
    hint_row: "Set key height and tilt angle (R1-R4). Shape varies by profile.",
    hint_fillet: "Round the four corners of the keycap (Squircle shape). Higher values = rounder.",
    hint_wall_thick: "Set the side wall thickness. Too thin reduces strength, too thick may interfere with switches.",
    hint_rib_shorten: "Set how much to raise the bottom of internal ribs. Adjust to prevent LED interference.",
    hint_enable_ribs: "Create cross-shaped reinforcement walls inside. Improves strength and prevents warping.",
    hint_homing_bump: "Create the tactile bump found on F and J keys for finger positioning.",
    hint_bump_type: "Choose bump shape: Round or Bar (rectangle).",
    hint_key_shape: "Select the base keycap shape. Supports rectangle, rounded, circle, polygon, star, and ISO Enter (L-shape).",
    hint_taper: "Adjust the top surface size. Smaller values = steeper taper.",
    hint_dish_type: "Set the dish shape for finger placement. Choose Cylindrical, Spherical, or Flat.",
    hint_texture: "Auto-generate surface textures like sandpaper or patterns.",
    hint_texture_global: "Apply texture to the entire keycap including sides, not just the top.",
    hint_twist: "Twist the entire keycap. Useful for artisan keycaps.",
    hint_tilt: "Fine-tune the top surface tilt in X and Z directions.",
    hint_img_upload: "Upload PNG or JPG images to apply as a texture on the keycap surface. Turn your favorite patterns or photos into keycap designs.",
    hint_custom_font: "Load font files converted to JSON format using tools like Facetype.js. *TTF or OTF files from your PC cannot be used directly.",
    hint_stem_diameter: "Adjust the outer diameter of the switch stem. Standard is 5.5mm.",
    hint_clearance: "Set the cross-hole tolerance. Increase if too tight to fit.",
    hint_stem_ext: "Extend only the stem below the bottom. For special switches or height adjustment.",
    hint_box_stem: "Add square walls around the cross stem for strength and dust protection (Kailh Box style).",
    hint_lego_stud: "Add LEGO-compatible studs on the top surface.",
    hint_enable_text: "Turn text generation ON/OFF.",
    hint_text_input: "Enter the character to engrave. Use line breaks for multiple lines.",
    hint_font: "Select the font for engraving.",
    hint_text_mode: "Choose Emboss (raised), Engrave (inset), Double-Shot (separate part), or Lithophane (backlit).",
    hint_text_height: "Set text thickness. For Double-Shot, this is the embed depth.",
    hint_conform: "Deform text to follow the keycap's top surface curve.",
    hint_align_preset: "One-click positioning to center, top-left, bottom-right, etc.",
    hint_text2: "Add a secondary smaller text, typically in the bottom-right corner.",
    hint_side_print: "Add text on the front side of the keycap.",
    hint_svg_upload: "Load vector images (.svg) for engraving. Perfect for logos and icons.",
    hint_svg_mode: "Choose SVG processing method. Double-Shot exports as separate parts for multi-color printing.",
    hint_strap_hole: "Cut a through-hole for pendants or keychains. Adjust position (X/Z), diameter and shape (circle / slot) freely; the slot variant adds length and rotation. While editing the hole is shown as a red translucent preview; the real cut appears once you stop adjusting.",
    // (Phase 11 cleanup: hint_workflow_guide / hint_qa_bar / hint_advanced_mode removed)
    hint_colors: "Change preview colors. *Does not affect STL output, but reflects in OBJ/3MF.",
    hint_url_share: "Encode current settings into a URL and copy. Share on social media.",
    hint_quick_save: "Temporarily save current settings in browser storage.",
    hint_export_json: "Save settings as a file. Load later or share with others.",
    hint_import_json: "Load saved setting files. Drag & drop multiple files to add to list.",
    hint_print_orient: "Rotate the entire model to match 3D print orientation.",
    hint_export_stl: "Save in standard 3D printer format (.stl).",
    hint_export_3mf: "Save with color information (.3mf). Ideal for Bambu Lab multi-color printing.",
    hint_export_parts: "Export parts separately as STL. Useful for printing with different filament colors.",
    hint_batch_list: "Enter comma-separated characters (A,B,C...) to auto-generate with current settings.",
    hint_batch_run: "Generate all characters in the list and download together.",
    hint_randomizer: "Randomly change all parameters. Great for finding new ideas.",
    hint_reset: "Reset all settings to defaults.",
    hint_import_stl: "Load custom 3D models (.stl) to combine.",
    hint_import_op: "Union adds geometry, Subtract carves out. *Subtract requires more processing time.",
    hint_simple_mode: "Simple Mode shows only essential settings for beginners. Advanced settings use V65 defaults.",
    hint_dimension_lines: "Display dimension lines on the 3D view. Useful for size verification before printing.",
    hint_layer_color: "Simulate color changes at filament swap height for Bambu Lab AMS and similar systems.",
    hint_visual_presets: "One-click setup for common keys (WASD, arrows, etc.).",
    hint_stock_icons: "Built-in common icons (arrows, play, Command key, etc.). No need to search for SVGs.",
    hint_tolerance_test: "Generate stems for printer tolerance testing. Useful for finding the optimal clearance value.",
    hint_sprue_kit: "Connect multiple keycaps like model kit runners. Perfect for gifts or sales.",
    hint_simple_key_size: "Easily select common key sizes with buttons.",
    hint_snapshot: "Save the current 3D view as an image.",
    hint_gallery_open: "Open the gallery of saved presets.",
    hint_gallery_save: "Save the current settings to the gallery.",
    hint_font_manager: "Open the custom font management dialog (.ttf/.otf/.woff).",
    hint_svg_manager: "Open the custom SVG management dialog.",
    hint_gumball: "Drag to adjust the position of text, SVG, or imported models.",
    hint_toggle_text: "Toggle text visibility on the 3D view.",
    hint_toggle_svg: "Toggle SVG visibility on the 3D view.",
    hint_stem_type: "Select the key switch stem type. Supports Cherry MX, Kailh Choc, Topre, Alps, etc.",
    hint_click_place: "Turn ON and click on the model to move text/icons to that position. Intuitive placement."
};

export const keycapHintVideos = {
    hint_unit_size: { type: 'video', src: 'videos/keycaphint/基本ピッチ.mp4' },
    hint_key_size: { type: 'video', src: 'videos/keycaphint/キーサイズ.mp4' },
    hint_stabilizer: { type: 'video', src: 'videos/keycaphint/スタビライザー.mp4' },
    hint_profile: { type: 'video', src: 'videos/keycaphint/プロファイル.mp4' },
    hint_row: { type: 'video', src: 'videos/keycaphint/行.mp4' },
    hint_fillet: { type: 'video', src: 'videos/keycaphint/フィレット.mp4' },
    hint_wall_thick: { type: 'video', src: 'videos/keycaphint/壁の厚み.mp4' },
    hint_rib_shorten: { type: 'video', src: 'videos/keycaphint/リブ短縮.mp4' },
    hint_enable_ribs: { type: 'video', src: 'videos/keycaphint/補強リブ.mp4' },
    hint_homing_bump: { type: 'video', src: 'videos/keycaphint/ホームポジション突起.mp4' },
    hint_bump_type: { type: 'video', src: 'videos/keycaphint/ホームポジション突起選択.mp4' },
    hint_key_shape: { type: 'video', src: 'videos/keycaphint/キー形状タイプ.mp4' },
    hint_taper: { type: 'video', src: 'videos/keycaphint/上面サイズ.mp4' },
    hint_dish_type: { type: 'video', src: 'videos/keycaphint/上面形状.mp4' },
    hint_texture: { type: 'video', src: 'videos/keycaphint/表面プロシージャル.mp4' },
    hint_img_upload: { type: 'video', src: 'videos/keycaphint/画像テクスチャ.mp4' },
    hint_stem_diameter: { type: 'video', src: 'videos/keycaphint/ステム外径.mp4' },
    hint_clearance: { type: 'video', src: 'videos/keycaphint/クリアランス.mp4' },
    hint_stem_ext: { type: 'video', src: 'videos/keycaphint/長さを拡張.mp4' },
    hint_box_stem: { type: 'video', src: 'videos/keycaphint/boxstem.mp4' },
    hint_lego_stud: { type: 'video', src: 'videos/keycaphint/レゴスタッド.mp4' },
    hint_randomizer: { type: 'video', src: 'videos/keycaphint/ランダマイザ.mp4' },
    hint_import_stl: { type: 'video', src: 'videos/keycaphint/stl読み込み.mp4' },
    hint_enable_text: { type: 'video', src: 'videos/keycaphint/文字を生成する.mp4' },
    hint_text_input: { type: 'video', src: 'videos/keycaphint/文字テキストボックス.mp4' },
    hint_font: { type: 'video', src: 'videos/keycaphint/フォント.mp4' },
    hint_custom_font: { type: 'video', src: 'videos/keycaphint/カスタムフォント.mp4' },
    hint_text_mode: { type: 'video', src: 'videos/keycaphint/文字生成モード.mp4' },
    hint_align_preset: { type: 'video', src: 'videos/keycaphint/文字配置プリセットボタン.mp4' },
    hint_text2: { type: 'video', src: 'videos/keycaphint/サブ文字スイッチ.mp4' },
    hint_side_print: { type: 'video', src: 'videos/keycaphint/サイド印字スイッチ.mp4' },
    hint_svg_upload: { type: 'video', src: 'videos/keycaphint/SVG読み込み.mp4' },
    hint_svg_mode: { type: 'video', src: 'videos/keycaphint/文字生成モード.mp4' },
    hint_colors: { type: 'video', src: 'videos/keycaphint/色設定.mp4' },
    hint_import_json: { type: 'video', src: 'videos/keycaphint/プリセット読み込み.mp4' },
    hint_dimension_lines: { type: 'video', src: 'videos/keycaphint/寸法線を表示.mp4' },
    hint_stock_icons: { type: 'video', src: 'videos/keycaphint/内蔵アイコンSVG.mp4' },
    hint_simple_icon: { type: 'video', src: 'videos/keycaphint/内蔵アイコンSVG.mp4' },
    hint_visual_presets: { type: 'video', src: 'videos/keycaphint/ビジュアルプリセット.mp4' },
    hint_simple_key_size: { type: 'video', src: 'videos/keycaphint/簡単モードキー幅.mp4' },
    hint_gumball: { type: 'video', src: 'videos/keycaphint/ガムボール.mp4' },
    hint_stem_type: { type: 'video', src: 'videos/keycaphint/軸タイプ.mp4' },
    hint_click_place: { type: 'video', src: 'videos/keycaphint/直感配置.mp4' }
};
