// =============================================
// KeybordStudio V1 - Keymap Studio export/import
// modules/keymap/keymap-export.js
// =============================================
// JSON / VIA .vil 形式で保存・読み込み。VIA Editor の .vil は内部的に
// gzip された JSON だが、ここでは可搬性重視で素の JSON を採用する。
// 互換性のためサブセットを VIA Editor JSON ("keymap.json") としても出力。

import { exportJSON, importJSON, getState } from './keymap-state.js';
import { formatKeycode, getKeycode } from './keymap-keycodes.js';

/**
 * .kbskeymap.json (KeybordStudio 標準形式) でファイル保存。
 */
export function downloadKeymapJSON(filename = 'keymap.kbskeymap.json') {
    const text = exportJSON();
    const blob = new Blob([text], { type: 'application/json' });
    _save(blob, filename);
}

/**
 * VIA Editor 互換 JSON を出力。VIA は keymap として
 * { "version": 1, "name", "vendorProductId", "macros": [...], "layers": [["KC_A", ...]] }
 * を要求する。
 */
export function downloadViaJSON(filename = 'keymap-via.json') {
    const s = getState();
    const layers = s.layers.map(layer =>
        layer.map(code => {
            const k = getKeycode(code);
            return k ? k.id : `0x${code.toString(16).toUpperCase().padStart(4,'0')}`;
        })
    );
    const macros = s.macros.map(actions => actions.map(a => {
        if (a.type === 'tap')   return { kc: getKeycode(a.code)?.id || a.code };
        if (a.type === 'down')  return { down: getKeycode(a.code)?.id || a.code };
        if (a.type === 'up')    return { up:   getKeycode(a.code)?.id || a.code };
        if (a.type === 'delay') return { delay: a.ms };
        if (a.type === 'text')  return { text:  a.text };
        return null;
    }).filter(Boolean));
    const payload = {
        version: 1,
        name: s.keyboardName,
        vendorProductId: 0,
        macros,
        layers
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    _save(blob, filename);
}

/**
 * QMK info.json fragment (matrix を含まない簡易版)。
 */
export function downloadQmkJSON(filename = 'keymap.qmk.json') {
    const s = getState();
    const out = {
        version: 1,
        keyboard: s.keyboardName,
        keymap: 'default',
        layout: s.physicalLayout || 'LAYOUT',
        layers: s.layers.map(layer =>
            layer.map(code => getKeycode(code)?.id || `KC_${formatKeycode(code).replace(/[^A-Z0-9]/g,'')}`)
        )
    };
    const blob = new Blob([JSON.stringify(out, null, 2)], { type: 'application/json' });
    _save(blob, filename);
}

/**
 * テキスト形式 (人間可読サマリー)。
 */
export function downloadTextSummary(filename = 'keymap.txt') {
    const s = getState();
    const lines = [];
    lines.push(`# ${s.keyboardName}`);
    lines.push(`Generated by KeybordStudio v1 — ${new Date().toISOString()}`);
    lines.push(`Layout: ${s.physicalLayout}`);
    lines.push('');
    s.layers.forEach((layer, i) => {
        lines.push(`## Layer ${i}`);
        // group keys by physical row for readability
        const rows = new Map();
        s.physicalKeys.forEach((k, idx) => {
            const r = Math.round(k.y);
            if (!rows.has(r)) rows.set(r, []);
            rows.get(r).push({ ...k, code: layer[idx] });
        });
        for (const [r, ks] of [...rows.entries()].sort((a,b) => a[0]-b[0])) {
            ks.sort((a, b) => a.x - b.x);
            lines.push(ks.map(k => formatKeycode(k.code).padEnd(8)).join(' '));
        }
        lines.push('');
    });
    if (s.macros.some(m => m.length)) {
        lines.push('## Macros');
        s.macros.forEach((m, i) => {
            if (!m.length) return;
            lines.push(`M${i}: ${m.map(a => {
                if (a.type === 'delay') return `${a.ms}ms`;
                if (a.type === 'text')  return `"${a.text}"`;
                return getKeycode(a.code)?.label || `0x${a.code?.toString(16)}`;
            }).join(' → ')}`);
        });
        lines.push('');
    }
    const blob = new Blob([lines.join('\r\n')], { type: 'text/plain' });
    _save(blob, filename);
}

/**
 * ファイルアップロード経由で読み込み。
 */
export async function importFromFile(file) {
    const text = await file.text();
    if (file.name.endsWith('.kbskeymap.json') || text.includes('keybordstudio.keymap')) {
        return importJSON(text);
    }
    // VIA Editor 形式
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed.layers) && parsed.layers.length) {
        // Convert layer arrays of KC_... strings to codes via getKeycode
        const keys = getState().physicalKeys;
        const layers = parsed.layers.slice(0, 4).map(layer =>
            layer.map(s => {
                if (typeof s === 'number') return s;
                const k = getKeycode(String(s));
                return k ? k.code : 0;
            })
        );
        // Pad to physicalKeys length
        const padded = layers.map(l => {
            const out = new Array(keys.length).fill(0x0001);
            for (let i = 0; i < Math.min(l.length, keys.length); i++) out[i] = l[i];
            return out;
        });
        return importJSON({
            kind: 'keybordstudio.keymap',
            keyboardName: parsed.name || 'Imported',
            physicalLayout: getState().physicalLayout,
            physicalKeys: keys,
            layers: padded,
            ledMode: 'rainbow_wave',
            ledHue: 0, ledSat: 1, ledBrightness: 200, ledSpeed: 128,
            ledPerKey: {},
            macros: (parsed.macros || []).map(m => (m || []).map(a => {
                if (a.kc)    return { type: 'tap',   code: getKeycode(a.kc)?.code || 0 };
                if (a.down)  return { type: 'down',  code: getKeycode(a.down)?.code || 0 };
                if (a.up)    return { type: 'up',    code: getKeycode(a.up)?.code || 0 };
                if (a.delay) return { type: 'delay', ms: a.delay };
                if (a.text)  return { type: 'text',  text: a.text };
                return null;
            }).filter(Boolean))
        });
    }
    throw new Error('Unrecognised keymap format.');
}

function _save(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default { downloadKeymapJSON, downloadViaJSON, downloadQmkJSON, downloadTextSummary, importFromFile };
